FROM quay.io/redhat-user-workloads/octo-edge-tenant/jetson-wheels-vllm-app:latest

RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && crb enable
RUN dnf install -y https://mirror.stream.centos.org/9-stream/CRB/aarch64/os/Packages/ladspa-1.13-28.el9.aarch64.rpm
RUN dnf install -y ffmpeg-free libSM libXext git-core

RUN uv pip install --no-cache-dir "git+https://github.com/mlcommons/inference.git@2814499#subdirectory=loadgen"

# install LDM
COPY . /diffusion
RUN cd /diffusion && uv pip install --no-cache-dir -r requirements.txt
